minetest-mods/homedecor_modpack

computer/computers.lua, homedecor/window_treatments.lua
*window_treatments.lua* : 
- Deleted plenty of redundant selection boxes
- Improved window quartered model (the inner cross was not adjusted to the texture)
- Applied appropriate breaking sounds
- Code style fix
*computers.lua* : 
- Code style fix (indentation, long lines, useless drop=, etc.)
- Deleted redundant selection boxes
- Applied appropriate breaking sounds
=> Cleaning cg72's code

homedecor/furniture.lua
... also remove useless definitions (set by default).
=> Allow sit on the office chairs

lrfurn/armchairs.lua, lrfurn/coffeetable.lua, lrfurn/endtable.lua, lrfurn/longsofas.lua, lrfurn/sofas.lua
=> Delete stack_max=1 in lrfurn

homedecor/furniture.lua
=> Beds : use default sleeping function and adjust s/c_box

homedecor/exterior.lua, homedecor/furniture.lua, lrfurn/armchairs.lua, lrfurn/longsofas.lua, lrfurn/sofas.lua
- Re-add params on openframe bookshelf (was out of the API).
- Adjust collision boxes on LRfurn's sofas and benches (all types).
=> Fix params (again)

computer/tetris.lua, fake_fire/init.lua, homedecor/bathroom_sanitation.lua, homedecor/beds.lua, homedecor/climate-control.lua, homedecor/clocks.lua, homedecor/depends.txt, homedecor/doors_and_gates.lua, homedecor/exterior.lua, homedecor/furniture.lua, homedecor/init.lua, homedecor/kitchen_appliances.lua, homedecor/kitchen_furniture.lua, homedecor/lighting.lua, homedecor/misc-nodes.lua, homedecor/wardrobe.lua, inbox/init.lua, itemframes/init.lua, lrfurn/longsofas.lua, lrfurn/sofas.lua, plasmascreen/init.lua
Consequently to https://github.com/minetest/minetest_game/commit/2824562dc94da588fd2bc21415bbc193972d93a0
=> Disallow partially or entirely some items to rotate and allow water to be picked up from well

computer/init.lua, fake_fire/init.lua, homedecor/init.lua, inbox/init.lua, itemframes/init.lua, lrfurn/init.lua, plasmascreen/init.lua, signs_lib/init.lua
... that prevented game from running on old MTG copies or if the modpack was partially enabled.
=> Fix screwdriver variables

computer/tetris.lua, fake_fire/init.lua, homedecor/electronics.lua, homedecor/misc-nodes.lua
- Rarer telephone ringing.
- Drinkable beer mug.
- fake_fire's smoke collides with nodes.
=> Minor tweaks

homedecor/books.lua, homedecor/exterior.lua, signs_lib/init.lua
* fixes sign_lib fence_with_signs to work again
* prevent several crash and item destruction scenarios
* makes sure to always return the itemstack
=> fix various crash scenarios and content_ignore related item destruction

chains/init.lua, computer/computers.lua, computer/init.lua, computer/tetris.lua, fake_fire/init.lua, homedecor/bathroom_sanitation.lua, homedecor/bedroom.lua, homedecor/books.lua, homedecor/climate-control.lua, homedecor/doors_and_gates.lua, homedecor/furniture.lua, homedecor/kitchen_appliances.lua, homedecor/kitchen_furniture.lua, homedecor/misc-nodes.lua, homedecor/office.lua, homedecor/window_treatments.lua, inbox/init.lua, itemframes/init.lua, lavalamp/init.lua, lrfurn/armchairs.lua, lrfurn/longsofas.lua, lrfurn/sofas.lua
=> Various maintenance and fixes

homedecor/handlers/inventory.lua, homedecor/trash_cans.lua, homedecor/wardrobe.lua, inbox/init.lua
Adds support for list rings, and fixes a mistake i made in 436fdfa causing mailbox's `can_dig` to always return false.
=> List rings

homedecor/doors_and_gates.lua
Fixes minetest-mods/homedecor_modpack #324
=> Resolve undeclared globals in calls to flip_gate.

lrfurn/coffeetable.lua
Fixes minetest-mods/homedecor_modpack #326
=> Fix coffeetable placement.

building_blocks/init.lua
Fixes minetest-mods/homedecor_modpack#316
=> Replace deprecated field

homedecor/climate-control.lua
=> Avoid crashes due to missing desk_fan entity.

homedecor/handlers/inventory.lua, inbox/init.lua, itemframes/init.lua
Other calls to check_player_privs were fixed as well.
Fixes #357
=> Fix calls to check_player_privs with player name instead of player userdata

homedecor/crafts.lua
And remove double craft definition
=> Make Wrought Iron Fence 2 recipe more generous

inbox/init.lua
Fixes inventory theft vulnerability discovered with client-side modding.
=> Verify inbox owner when taking items

building_blocks/depends.txt, building_blocks/init.lua
Stairs replace bbstairs
And and one functions for creates all cut blocks.
=> Simplify integration moreblocks and stairs in building blocks

building_blocks/alias.lua
Alias for old node Tar cut by moreblocks.
=> Building_blocks Alias
